workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-email

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/go
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: plugins/docker
    repo: plugins/email
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Email
  desc: Send build status notifications via Email
  type: notify
  image: plugins/drone-email
  labels:
    - email
