kind: pipeline
type: docker
name: status

steps:
- name: send preview mail
  image: jonasbernard/drone-email
  when:
    event:
    - promote
    - custom
    status:
    - success
    - failure
  settings:
    from.address:
      from_secret: ORG_MAIL_FROM_ADDRESS
    from.name:
      from_secret: ORG_MAIL_FROM_NAME
    host: 
      from_secret: ORG_MAIL_SMTP_SERVER
    recipients_only: true
    recipients:
      from_secret: ORG_MAIL_RECIPIENTS
    username:
      from_secret: ORG_MAIL_SMTP_USERNAME
    password:
      from_secret: ORG_MAIL_SMTP_PASSWORD
