build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-email
    when:
      branch: master

plugin:
  name: Email
  desc: Send build status notifications via Email
  type: notify
  image: plugins/drone-email
  labels:
    - email
